services:
  # MongoDB Service
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - ecommerce-network

  # Redis Service
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  ecommerce-network:
    driver: bridge
